import { BikeSpec, ChartDataPoint, BikePart, ConfigOption } from "./types";

export const HAVOCKER_SPECS: BikeSpec[] = [
  { item: "Model Name", value: "Havocker", detail: "Electric Dirtbike (L3e)" },
  { item: "0-50km Accel", value: "2.1s", highlight: true },
  { item: "Peak Power", value: "21KW", detail: "8000rpm High Perf. Brushless", highlight: true },
  { item: "Max Torque", value: "550N.m", highlight: true },
  { item: "Battery", value: "72V/58Ah", detail: "Quick Removable" },
  { item: "Range", value: "100km", detail: "@50km/h" },
  { item: "Charge Time", value: "2.5 Hours", detail: "22A Charger" },
  { item: "Max Speed", value: "100km/h" },
  { item: "Net Weight", value: "89KG" },
  { item: "Seat Height", value: "900mm" },
  { item: "Ground Clearance", value: "315mm" },
  { item: "Launch Date", value: "NOV 2025" },
];

export const POWER_CURVE: ChartDataPoint[] = [
  { name: "0", value: 0, secondary: 550 },
  { name: "1000", value: 5, secondary: 550 },
  { name: "2000", value: 12, secondary: 540 },
  { name: "3000", value: 16, secondary: 520 },
  { name: "4000", value: 19, secondary: 480 },
  { name: "5000", value: 20.5, secondary: 420 },
  { name: "6000", value: 21, secondary: 350 },
  { name: "7000", value: 20.8, secondary: 280 },
  { name: "8000", value: 19.5, secondary: 200 },
];

export const CHASSIS_SPECS = [
  { label: "Frame", value: "Alloy w/ Carbon Fiber" },
  { label: "Front Shock", value: "Adjustable Inverted" },
  { label: "Rear Shock", value: "Adjustable w/ Airbag" },
  { label: "Brakes", value: "Hydraulic Disc" },
];

export const BIKE_PARTS: BikePart[] = [
  {
    id: "motor",
    label: "DRIVE MOTOR",
    description: "Smooth, high-torque brushless motor tuned for instant acceleration.",
    specs: [{ label: "Power", value: "21KW" }, { label: "Torque", value: "550N.m" }],
    coordinates: { x: 50, y: 65 },
  },
  {
    id: "battery",
    label: "BATTERY SYSTEM",
    description: "Long-range 72V pack with easy swap capability for endless riding.",
    specs: [{ label: "Capacity", value: "58Ah" }, { label: "Voltage", value: "72V" }],
    coordinates: { x: 45, y: 45 },
  },
  {
    id: "suspension",
    label: "SUSPENSION",
    description: "Plush, adjustable forks designed to handle any terrain comfortably.",
    specs: [{ label: "Travel", value: "200mm" }, { label: "Type", value: "Air/Oil" }],
    coordinates: { x: 25, y: 70 },
  },
  {
    id: "chassis",
    label: "HYBRID FRAME",
    description: "Lightweight alloy and carbon fiber blend for agile handling.",
    specs: [{ label: "Material", value: "Alloy/Carbon" }, { label: "Weight", value: "89KG" }],
    coordinates: { x: 60, y: 50 },
  },
];

export const CONFIG_OPTIONS: ConfigOption[] = [
  { id: "supermoto_wheels", label: "Supermoto Wheels", price: 750, type: "upgrade", detail: "17″ Slick / Road-Optimized" },
];

export const BASE_PRICE = 6999;

export const BLOG_POSTS = [
  {
    id: 1,
    title: "MOJAVE DESERT TELEMETRY REPORT",
    subtitle: "94% thermal efficiency at 45°C ambient. Full breakdown of our Mojave endurance run.",
    category: "ENGINEERING",
    date: "OCT 24, 2025",
    image: "/images/gallery-1.jpg",
    hoverImage: "/images/gallery-2.jpg",
    featured: true,
  },
  {
    id: 2,
    title: "THE FUTURE OF ELECTRIC FREEDOM",
    subtitle: "How the HAVØK X1 is rewriting the rules for off-road electric performance.",
    category: "LIFESTYLE",
    date: "OCT 20, 2025",
    image: "/images/gallery-2.jpg",
    hoverImage: "/images/gallery-3.jpg",
    featured: true,
  },
  {
    id: 3,
    title: "URBAN ASSAULT: X1 IN THE CITY",
    subtitle: "Street-legal L3e credentials meet daily commuter practicality.",
    category: "TECH",
    date: "OCT 15, 2025",
    image: "/images/gallery-3.jpg",
    hoverImage: "/images/gallery-1.jpg",
    featured: false,
  },
  {
    id: 4,
    title: "REDEFINING TORQUE VECTORING",
    subtitle: "Inside the software that gives the X1 its telepathic throttle response.",
    category: "ENGINEERING",
    date: "OCT 12, 2025",
    image: "/images/gallery-1.jpg",
    hoverImage: "/images/gallery-3.jpg",
    featured: false,
  },
  {
    id: 5,
    title: "BATTERY TECH DEEP DIVE",
    subtitle: "72V architecture explained — swappable packs, BMS telemetry, and thermal management.",
    category: "ENGINEERING",
    date: "OCT 8, 2025",
    image: "/images/gallery-2.jpg",
    hoverImage: "/images/gallery-1.jpg",
    featured: false,
  },
  {
    id: 6,
    title: "TRAIL RIDING WITH THE X1",
    subtitle: "Weekend warriors share their first 100km on single-track.",
    category: "LIFESTYLE",
    date: "OCT 5, 2025",
    image: "/images/gallery-3.jpg",
    hoverImage: "/images/gallery-2.jpg",
    featured: false,
  },
  {
    id: 7,
    title: "OTA UPDATE V2.1 CHANGELOG",
    subtitle: "Sport mode refinements, regen curves, and new dashboard telemetry.",
    category: "TECH",
    date: "OCT 1, 2025",
    image: "/images/gallery-1.jpg",
    hoverImage: "/images/gallery-2.jpg",
    featured: false,
  },
  {
    id: 8,
    title: "SUPERMOTO CONVERSION GUIDE",
    subtitle: "Everything you need to go from dirt to street in under an hour.",
    category: "TECH",
    date: "SEP 28, 2025",
    image: "/images/gallery-2.jpg",
    hoverImage: "/images/gallery-3.jpg",
    featured: false,
  },
  {
    id: 9,
    title: "RIDER SPOTLIGHT: VOLTA RACING",
    subtitle: "How the Volta team preps their X1 fleet for competition.",
    category: "LIFESTYLE",
    date: "SEP 25, 2025",
    image: "/images/gallery-3.jpg",
    hoverImage: "/images/gallery-1.jpg",
    featured: false,
  },
  {
    id: 10,
    title: "REGENERATIVE BRAKING EXPLAINED",
    subtitle: "Capturing energy on every descent — the physics behind regen.",
    category: "ENGINEERING",
    date: "SEP 22, 2025",
    image: "/images/gallery-1.jpg",
    hoverImage: "/images/gallery-3.jpg",
    featured: false,
  },
  {
    id: 11,
    title: "COLD WEATHER PERFORMANCE",
    subtitle: "Sub-zero testing in Norway. How the X1 handles extreme conditions.",
    category: "ENGINEERING",
    date: "SEP 18, 2025",
    image: "/images/gallery-2.jpg",
    hoverImage: "/images/gallery-1.jpg",
    featured: false,
  },
  {
    id: 12,
    title: "COMMUNITY BUILD GALLERY",
    subtitle: "Custom builds, liveries, and mods from the HAVØK community.",
    category: "LIFESTYLE",
    date: "SEP 15, 2025",
    image: "/images/gallery-3.jpg",
    hoverImage: "/images/gallery-2.jpg",
    featured: false,
  },
];

export const FORUM_THREADS = [
  {
    id: 1,
    title: "OPTIMAL TIRE PRESSURE FOR SAND DUNES?",
    author: "SAND_RAIDER",
    category: "TECH",
    time: "2H AGO",
    replies: 24,
    pinned: true,
  },
  {
    id: 2,
    title: "FIRST 500KM REVIEW: L3e PERFORMANCE",
    author: "VOLT_RIDER",
    category: "ENGINEERING",
    time: "5H AGO",
    replies: 12,
    pinned: false,
  },
  {
    id: 3,
    title: "BEST AFTERMARKET PEGS FOR GRIP?",
    author: "DIRT_KING",
    category: "TECH",
    time: "1D AGO",
    replies: 8,
    pinned: false,
  },
  {
    id: 4,
    title: "CUSTOM LIVERY GALLERY - SHOW YOUR X1",
    author: "DESIGN_LAB",
    category: "LIFESTYLE",
    time: "2D AGO",
    replies: 56,
    pinned: false,
  },
];
